"""
schemas.py — Pydantic request and response models for the unhookd API.

Defines the shape of data flowing in and out of the analysis endpoints.
All fields are typed and validated by Pydantic before reaching business logic.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, HttpUrl, field_validator
import re



# Request Models


class EmailAnalysisRequest(BaseModel):
    """
    Payload sent to /analyze/email.

    Attributes:
        sender:     The sender's email address.
        subject:    The email subject line.
        body:       The plain-text body of the email.
        links:      List of URLs extracted from the email body / headers.
    """
    sender: str
    subject: str
    body: str
    links: Optional[List[str]] = []

    @field_validator("links")
    @classmethod
    def links_default_empty_list(cls, v):
        # Ensure links is a list (Pydantic may pass None)
        return v or []

    @field_validator("sender")
    @classmethod
    def validate_sender_basic(cls, v: str) -> str:
        # Content extraction in browser email clients is often partial.
        # Accept empty / display-name sender values so analysis can still run.
        if not isinstance(v, str):
            raise ValueError("sender must be a string")
        v = v.strip()
        if not v:
            return "unknown@unknown.local"

        # Extract an address from common display-name formats like:
        # "Acme Support <support@example.com>"
        match = re.search(r"([^\s<>@]+@[^\s<>@]+\.[^\s<>@]+)", v)
        if match:
            return match.group(1).strip()

        # If there is no email-like token, keep a deterministic placeholder
        # so downstream heuristics still receive a valid sender field.
        if "@" not in v:
            local_part = re.sub(r"[^a-z0-9]+", ".", v.lower()).strip(".") or "unknown"
            return f"{local_part}@unknown.local"

        # Simple regex to check for local@domain structure
        if not re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", v):
            raise ValueError("sender must be a valid email-like address")
        return v


class LinkAnalysisRequest(BaseModel):
    """
    Payload sent to /analyze/link.

    Attributes:
        url:    The full URL string to be analysed.
    """
    url: HttpUrl

    # HttpUrl already validates and normalises the url; no extra validator needed



# Response Models


class EmailAnalysisResponse(BaseModel):
    """
    Response returned from /analyze/email.

    Attributes:
        severity:        AI-classified severity level.
        flags:           List of human-readable risk indicators detected.
        ai_explanation:  Plain-English summary generated by Gemini (or stub).
        education_tip:   Actionable advice generated by Gemini (or stub).
    """
    severity: Literal["no_risk", "low", "medium", "high", "critical"]
    flags: List[str]                    # e.g. ["Urgent language", "Suspicious domain"]
    ai_explanation: str                 # Gemini-generated or placeholder explanation
    education_tip: str                  # Gemini-generated or placeholder learning tip


class LinkAnalysisResponse(BaseModel):
    """
    Response returned from /analyze/link.

    Attributes:
        severity:        AI-classified severity level.
        flags:           List of human-readable risk indicators detected.
        ai_explanation:  Plain-English summary generated by Gemini (or stub).
    """
    severity: Literal["no_risk", "low", "medium", "high", "critical"]
    flags: List[str]
    ai_explanation: str


class DownloadAnalysisRequest(BaseModel):
    """
    Payload sent to /analyze/download.

    Attributes:
        url:           The download URL to be analysed.
        filename:      Optional filename suggested by the server or client.
        content_type:  Optional MIME type reported for the download.
    """
    url: HttpUrl
    filename: Optional[str] = None
    content_type: Optional[str] = None
    # HttpUrl validates the URL format; keep model simple


class DownloadAnalysisResponse(BaseModel):
    """
    Response returned from /analyze/download.

    Attributes:
        severity:        AI-classified severity level.
        flags:           List of human-readable risk indicators detected.
        ai_explanation:  Plain-English summary generated by Gemini (or stub).
        education_tip:   Actionable advice generated by Gemini (or stub).
    """
    severity: Literal["no_risk", "low", "medium", "high", "critical"]
    flags: List[str]
    ai_explanation: str
    education_tip: str
