"""
schemas.py — Pydantic request and response models for the unhookd API.

Defines the shape of data flowing in and out of the analysis endpoints.
All fields are typed and validated by Pydantic before reaching business logic.
"""

from typing import List, Optional
from pydantic import BaseModel, HttpUrl, field_validator


# ---------------------------------------------------------------------------
# Request Models
# ---------------------------------------------------------------------------

class EmailAnalysisRequest(BaseModel):
    """
    Payload sent to /analyze/email.

    Attributes:
        sender:     The sender's email address.
        subject:    The email subject line.
        body:       The plain-text body of the email.
        links:      List of URLs extracted from the email body / headers.
    """
    sender: str
    subject: str
    body: str
    links: Optional[List[str]] = []

    @field_validator("sender")
    @classmethod
    def sender_must_not_be_empty(cls, v: str) -> str:
        # TODO: Add stricter email format validation if needed
        if not v.strip():
            raise ValueError("sender must not be empty")
        return v.strip()


class LinkAnalysisRequest(BaseModel):
    """
    Payload sent to /analyze/link.

    Attributes:
        url:    The full URL string to be analysed.
    """
    url: str

    @field_validator("url")
    @classmethod
    def url_must_not_be_empty(cls, v: str) -> str:
        # TODO: Consider coercing bare domains into full URLs here
        if not v.strip():
            raise ValueError("url must not be empty")
        return v.strip()


# ---------------------------------------------------------------------------
# Response Models
# ---------------------------------------------------------------------------

class EmailAnalysisResponse(BaseModel):
    """
    Response returned from /analyze/email.

    Attributes:
        risk_score:      Integer 0–100. Higher = more suspicious.
        flags:           List of human-readable risk indicators detected.
        ai_explanation:  Plain-English summary generated by Gemini (or stub).
        education_tip:   Actionable advice generated by Gemini (or stub).
    """
    risk_score: int                     # 0 = safe, 100 = highly suspicious
    flags: List[str]                    # e.g. ["Urgent language", "Suspicious domain"]
    ai_explanation: str                 # Gemini-generated or placeholder explanation
    education_tip: str                  # Gemini-generated or placeholder learning tip


class LinkAnalysisResponse(BaseModel):
    """
    Response returned from /analyze/link.

    Attributes:
        risk_score:      Integer 0–100. Higher = more suspicious.
        flags:           List of human-readable risk indicators detected.
        ai_explanation:  Plain-English summary generated by Gemini (or stub).
    """
    risk_score: int
    flags: List[str]
    ai_explanation: str
